# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0fecee3dea97fa56f3c41eabf7078878bbebac0cc5c32e5551900ab73e9772d81e6055396df8a4dc670fd61f2710c785227a18bec6856915410aaed635089418

test:
  secret_key_base: 1e6b39ff40db7452db1ddd2c27d93fe29a7dae663f8ec6908d831ccf8ae9578c2f75fd9cafc39a306261d6567e1b6b2fe1542e2dc1c90aeac766ea48902ef8f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
